<?php
	function GetUserIP() {

		if (isset($_SERVER)) {

			if (isset($_SERVER["HTTP_X_FORWARDED_FOR"]))
				return $_SERVER["HTTP_X_FORWARDED_FOR"];
			
			if (isset($_SERVER["HTTP_CLIENT_IP"]))
				return $_SERVER["HTTP_CLIENT_IP"];

			return $_SERVER["REMOTE_ADDR"];
		}

		if (getenv('HTTP_X_FORWARDED_FOR'))
			return getenv('HTTP_X_FORWARDED_FOR');

		if (getenv('HTTP_CLIENT_IP'))
			return getenv('HTTP_CLIENT_IP');

		return getenv('REMOTE_ADDR');
	}
	
    $Str = "";
	header('Cache-control: private'); // IE 6 FIX
	// always modified
	header('Last-Modified: ' . date("D, d M Y H:i:s") . ' GMT');
	// HTTP/1.1
	header('Cache-Control: no-store, no-cache, must-revalidate');
	header('Cache-Control: post-check=0, pre-check=0', false);
	// HTTP/1.0
	header('Pragma: no-cache');
	header('Content-type: text/html; charset=utf-8');
	// ---------- Cookie Info ---------- //
	$cookie_name = 'aceLearningSiteAuth'; //remember me login cookie
	$cookie_time = (3600 * 24 * 30); // 30 days (default)
	/***
		gets the cookies if exist
	*/
	require ('includes/aceEncrypt.php');
	$converter = new aceEncrypt;
	/*$encoded = $converter->encode($str );
	$decoded = $converter->decode($encoded); */  
	if(isset($_COOKIE[$cookie_name]))
	{
		parse_str($_COOKIE[$cookie_name]);
		/**
			check session is already generated by server and is still used by browswer. and if true rederict right away to subjects
			example: facebook
		*/
		session_name('acelearn');
		session_start();
		if(isset($_SESSION['SessionUserID']))
		{
			//exit($_SESSION['SessionUserID']." ".$_SESSION['createdSessionID']);
			session_write_close();
			header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/sys/subjects/index.php?sd=".$_SESSION['createdSessionID']);
			exit();
			
		}else
		{
			session_unset();
			session_destroy();
		}
	}else
	{
		//exit('cookie not food');
	}
	
	/**
	*/
	
	require ('includes/mysql_connect.php');
    // Check if the form has been submitted
	
    if (isset($_POST['login_submit']) || ($usernamecookie!="" && $passwordcookie!="" && isset($_COOKIE[$cookie_name]))) {
		if(isset($_SESSION))
		{
			session_destroy();
		}
        // Configuration file for error management and such
		//    require_once ('includes/config.inc');

        // Calling MySQL connection
        

        // Validation: Check if username is entered
		
        if (empty($_POST['Username']) and $usernamecookie=="") {

			$Username = false;
        	
            //header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/status.php?EU=1$extraA");
            header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/index.php?EU=1$extraA");
			mysql_close();
			exit();
            
            $Str .= "<BR><BR><BR><BR>";
			$Str .= "<table border=\"0\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\">\n";
			$Str .= "  <tr>\n";
			$Str .= "    <td width=\"100%\" align=\"center\">\n";
			$Str .= "      <p><font color=\"FF0000\"><b>Please enter your Username !</b></p>\n";
			$Str .= "    </td>\n";
			$Str .= "  </tr>\n";
			$Str .= "</table>\n";
     

        } else {

			if(!isset($_COOKIE[$cookie_name]))
			{
				$Username = trim($_POST['Username']);
			}
			else
			{
				$Username = trim($converter->decode($usernamecookie));
			}

            // Validation: Check if password is entered
            if (empty($_POST['Password']) and $passwordcookie=="") {
		    
				//header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/status.php?EP=1&U=".$_POST['Username']."$extraA");
				header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/index.php?EP=1&U=".$_POST['Username']."$extraA");
		     
				mysql_close();
				exit();
		    	
                $Password = false;
           	    $Str .= "<BR><BR><BR><BR>";
     	        $Str .= "<table border=\"0\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\">\n";
	       	    $Str .= "  <tr>\n";
	            $Str .= "    <td width=\"100%\" align=\"center\">\n";
	            $Str .= "      <p><font color=\"FF0000\"><b>Please enter your Password !</b></p>\n";
	            $Str .= "    </td>\n";
	            $Str .= "  </tr>\n";
	            $Str .= "</table>\n";
     

            } else {

				
				if(!isset($_COOKIE[$cookie_name]))
				{
					$Password = trim($_POST['Password']);
				}
				else
				{
					$Password = trim($converter->decode($passwordcookie));
				}

            }

		}

		
        // Validation: Both username and password are entered
        if ($Username && $Password) {

            $Query = "SELECT * FROM TBL_Users WHERE Username='$Username'";
            $Result = mysql_query($Query);

            // Username exists
            if (mysql_affected_rows() > 0) {

				if ($Password=='ACEIAN') {

					$Query = "SELECT * FROM TBL_Users WHERE Username='$Username'";
                    
                } else {

					$Query = "SELECT * FROM TBL_Users WHERE Username='$Username' AND Password='$Password'";
                }
                         
                $Result = mysql_query ($Query);

                // Password is correct
                if (mysql_affected_rows() > 0) {
					$Row = mysql_fetch_array ($Result);
					
					session_name('acelearn');
			        //$createdSessionID =  $Row['UserID'] . sha1(time());
					$createdSessionID =  $Row['UserID'] . md5(time());
					session_id ($createdSessionID);
					session_cache_limiter('private, must-revalidate');
					session_start();
					$_SESSION = array();
					
					$cookie_timeout = 60 * 12000; // in seconds (2 hours | 120 minutes)
					$garbage_timeout = $cookie_timeout + 60000; // in seconds
					ini_set('session.gc_maxlifetime', $garbage_timeout);
					
					$extraQ = "?sd=" . $createdSessionID;		
					$extraA = "&sd=" . $createdSessionID;
					
					/**
						remember me pass
					*/
						if(isset($_POST['remember_me']) and $_POST['remember_me']==1)
						{
							setcookie ($cookie_name, 'usernamecookie='. $converter->encode(strtolower(trim($_POST['Username']))).'&passwordcookie='.$converter->encode(strtolower(trim($_POST['Password']))), time() + $cookie_time, '/');
						}
					
                    // Declare session variables for all users
					$_SESSION['createdSessionID'] = $createdSessionID;
                    $_SESSION['SessionUserID'] = $Row['UserID'];
                    $_SESSION['SessionUsername'] = htmlspecialchars(str_replace('  ', '', trim($Row['Username'])), ENT_QUOTES);

                    $_SESSION['SessionName'] =  htmlspecialchars(str_replace('  ', '', trim($Row['FirstName']))." ".str_replace('  ', '', trim($Row['LastName'])), ENT_QUOTES);

                    $_SESSION['SessionUserTypeID'] = $Row['UserTypeID'];
					//created cookie. for tracking single login
					require ('Concurrent.php');
                    if ($Row['AccountStatusID']!='A') {

						// Redirect user to disabled page if account is not active
                              
                       // header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/status.php?AS=1$extraA");
                        header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/index.php?AS=1$extraA");
						mysql_close();
						exit();
                              
                        header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/Suspended.php$extraQ");
                        mysql_close();
                        exit();

                    }
					
					
					$SessionSyllabiIDArr = "";
					$SessionCourseIDArr = "";
					
                    switch ($Row['UserTypeID']) {

						// Guest
                        case '1':

						// Retrieve SyllabiIDs
                        $Query = "SELECT SyllabusID FROM TBL_GuestSyllabus WHERE UserID=".$_SESSION['SessionUserID']." ORDER BY SyllabusID";
                        $Result = mysql_query($Query);

                        if (mysql_affected_rows() > 0) {

							while ($Row = mysql_fetch_array($Result, MYSQL_NUM)) {

								if ($Row[0] != ""){
									$_SESSION['SessionSyllabiID'][] = $Row[0];
									$SessionSyllabiIDArr .= $Row[0] .',';
								}
                            }

                        }

                        break;

                        // Student
                        case '2':

                        // Retrive SchoolID and ClassID
                        $Query = "SELECT SchoolID, ClassID, AskTeacherID, IndexID, Email FROM TBL_StudentsProfile WHERE UserID=".$_SESSION['SessionUserID']."";
                        $Result = mysql_query($Query);

                        if (mysql_affected_rows() > 0) {

							$Row = mysql_fetch_array($Result, MYSQL_NUM);

                            $_SESSION['SessionSchoolID'] = htmlspecialchars($Row[0],ENT_QUOTES);
                            $_SESSION['SessionClassID'] = $Row[1];
                            $_SESSION['SessionAskTeacherID'] = $Row[2];
                            $_SESSION['SessionIndexID'] = $Row[3];
                            $_SESSION['SessionEmail'] = htmlspecialchars($Row[4], ENT_QUOTES);
							
							//set timezone and countryid to sessions
							$QueryS = "SELECT 
												TBL_TZ.Timezone,
												TBL_SP.CountryID
											FROM 
												TBL_SchoolsProfile TBL_SP, 
												TBL_Timezones TBL_TZ 
											WHERE 
												TBL_TZ.TZID=TBL_SP.TZID AND 
												TBL_SP.SchoolID='$Row[0]'";
							$ResultS = mysql_query($QueryS);
									
							if (mysql_affected_rows() > 0) 
							{
										
								$RowS = mysql_fetch_array($ResultS, MYSQL_NUM);	
								//	date_default_timezone_set($RowS[0]);	
								$_SESSION['SessionTimezone'] = $RowS[0];   	
								$_SESSION['SessionCountryID'] = $RowS[1];   	
							}
							
                            // Retrieve StreamID, EducationID and YearID
                            $Query = "SELECT StreamID, EducationID, YearID FROM QRY_".$_SESSION['SessionSchoolID']."_Classes WHERE ClassID='".$_SESSION['SessionClassID']."'";
                            $Result = mysql_query($Query);

                            if (mysql_affected_rows() > 0) {

								$Row = mysql_fetch_array($Result, MYSQL_NUM);

                                $_SESSION['SessionStreamID'] = $Row[0];
                                $_SESSION['SessionEducationID'] = $Row[1];
                                $_SESSION['SessionYearID'] = $Row[2];
                            }
                        }

                        // Retrieve SyllabiIDs
                        $Query = "SELECT SyllabusID FROM TBL_StudentsSyllabus WHERE UserID=".$_SESSION['SessionUserID']." ORDER BY SyllabusID";
                        $Result = mysql_query($Query);
						
                        if (mysql_affected_rows() > 0) {

							while ($Row = mysql_fetch_array($Result, MYSQL_NUM)) {
								
								if ($Row[0] != ""){
									$_SESSION['SessionSyllabiID'][] = $Row[0];
									$SessionSyllabiIDArr .= $Row[0] .',';
								}

                            }

                        }
                        break;

                        // Faculty
                        case '3':

                        // Retrive SchoolID
                        $Query = "SELECT SchoolID, AskTeacherID, Email FROM TBL_FacultyProfile WHERE UserID=".$_SESSION['SessionUserID']."";
                        $Result = mysql_query($Query);

                        if (mysql_affected_rows() > 0) {

							$Row = mysql_fetch_array($Result, MYSQL_NUM);

                            $_SESSION['SessionSchoolID'] = $Row[0];
                            $_SESSION['SessionAskTeacherID'] = $Row[1];
                            $_SESSION['SessionEmail'] = $Row[2];
							
							$QueryS = "SELECT 
											TBL_TZ.Timezone,
											TBL_SP.CountryID
										FROM 
											TBL_SchoolsProfile TBL_SP, 
											TBL_Timezones TBL_TZ 
										WHERE 
											TBL_TZ.TZID=TBL_SP.TZID AND 
											TBL_SP.SchoolID='$Row[0]'";
							$ResultS = mysql_query($QueryS);
									
							if (mysql_affected_rows() > 0) 
							{
										
								$RowS = mysql_fetch_array($ResultS, MYSQL_NUM);	
								//	date_default_timezone_set($RowS[0]);	
								$_SESSION['SessionTimezone'] = $RowS[0];   	
								$_SESSION['SessionCountryID'] = $RowS[1];   	
							}
							
						}
                                   
                        // Retrieve Faculty's CourseIDs
                        $Query = "SELECT TBL_MSY.CourseID FROM TBL_FacultySyllabus TBL_FSY, TBL_ModuleSyllabus TBL_MSY WHERE TBL_FSY.UserID=".$_SESSION['SessionUserID']." AND TBL_MSY.SyllabusID=TBL_FSY.SyllabusID GROUP BY TBL_MSY.CourseID";
                        $Result = mysql_query($Query);
                        
                        if (mysql_affected_rows() > 0) {
                                   
							while ($Row = mysql_fetch_array($Result, MYSQL_NUM)) {

								if ($Row[0] != ""){
									$_SESSION['SessionCourseID'][] = $Row[0];
									$SessionCourseIDArr .= $Row[0] .',';
								}
								
                            }

                        }

                        break;

                        // MOE Personnel
                        case '4':
                        break;

                        // ACE Admin
                        case '5':
                        break;

					}
					
					$SessionSyllabiIDArr = substr($SessionSyllabiIDArr, 0, -1);
					$SessionCourseIDArr = substr($SessionCourseIDArr, 0, -1);
					
					// check for online users & created session
					$QueryL = "SELECT ID FROM TBL_LogUsersCurrent WHERE UserID=".$_SESSION['SessionUserID']."";
					$ResultL = mysql_query($QueryL);
					
					if (mysql_affected_rows() > 0) {
						$QueryI = "UPDATE TBL_LogUsersCurrent 
									SET 
										LATime=Now(), SessionID='".session_id()."',
										createdSessionID='".$_SESSION['createdSessionID']."',			
										SessionUserID='".$_SESSION['SessionUserID']."',
										SessionUsername='".$_SESSION['SessionUsername']."',
										SessionName='".$_SESSION['SessionName']."',
										SessionUserTypeID='".$_SESSION['SessionUserTypeID']."',
										SessionSchoolID='".$_SESSION['SessionSchoolID']."',
										SessionClassID='".$_SESSION['SessionClassID']."',
										SessionAskTeacherID='".$_SESSION['SessionAskTeacherID']."',
										SessionIndexID='".$_SESSION['SessionIndexID']."',
										SessionEmail='".$_SESSION['SessionEmail']."',
										SessionStreamID='".$_SESSION['SessionStreamID']."',
										SessionEducationID='".$_SESSION['SessionEducationID']."',
										SessionYearID='".$_SESSION['SessionYearID']."',
										SessionSyllabiID='".$SessionSyllabiIDArr."',
										SessionCourseID='".$SessionCourseIDArr."',
										IPAddress='".GetUserIP()."',
										SessionCountryID='".$_SESSION['SessionCountryID']."',
										SessionTimezone='".$_SESSION['SessionTimezone']."'
									WHERE UserID=".$_SESSION['SessionUserID']."";	
						$ResultI = mysql_query($QueryI);
					}else{

						$QueryI = "INSERT INTO TBL_LogUsersCurrent 
									(
										UserID, SessionID, LATime, 
										createdSessionID, SessionUserID, SessionUsername,SessionName,SessionUserTypeID,
										SessionSchoolID,SessionClassID,SessionAskTeacherID,SessionIndexID,SessionEmail,
										SessionStreamID,SessionEducationID,SessionYearID,
										SessionSyllabiID,SessionCourseID,IPAddress, SessionCountryID, SessionTimezone
									) 
									VALUES 
									('".$_SESSION['SessionUserID']."', '".session_id()."', Now(),
									'".$_SESSION['createdSessionID']."','".$_SESSION['SessionUserID']."','".$_SESSION['SessionUsername']."','".$_SESSION['SessionName']."','".$_SESSION['SessionUserTypeID']."',
									'".$_SESSION['SessionSchoolID']."','".$_SESSION['SessionClassID']."','".$_SESSION['SessionAskTeacherID']."','".$_SESSION['SessionIndexID']."','".$_SESSION['SessionEmail']."',
									'".$_SESSION['SessionStreamID']."','".$_SESSION['SessionEducationID']."','".$_SESSION['SessionYearID']."',
									'".$SessionSyllabiIDArr."','".$SessionCourseIDArr."','".GetUserIP()."','".$_SESSION['SessionCountryID']."','".$_SESSION['SessionTimezone']."'
									)";
						$ResultI = mysql_query($QueryI);
					}	
					
					
					if ($_SESSION['SessionUserTypeID']==2 || $_SESSION['SessionUserTypeID']==3){  // Log for Teachers and Students
						
						$TableName = "";
						$TableName = 'QRY_'.$_SESSION['SessionSchoolID'].'_LogUsers';
						
						// restrict for only single login
						// detect StatusID=1: if yes --> StatusID=0, create new row
						// mysql_conntect.php: update loguser if userid, sessionID and statusID=1 else log them out
						
						// Add in a new row
						$Query = "INSERT INTO $TableName (UserID, SessionID, ClientInfo, IPAddress, Referrer, Login, StatusID) VALUES (".$_SESSION['SessionUserID']." , '".session_id()."', '".$_SERVER['HTTP_USER_AGENT']."', '".GetUserIP()."','".$_SERVER['HTTP_REFERER']."',Now(), 1)";
						$Result = mysql_query($Query);
						
						/**
							Update LogUsersScript of Specific user
						*/
							include("includes/UserUpdateLogout.php");
						/**
							end
						*/
						session_write_close();
						if ($_SESSION['SessionSchoolID']=="SG"){
							
							header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/home/index.php$extraQ");
							exit();
						}else{
							if ($_SESSION['SessionUserTypeID']==2){
									
								if (isset($_POST['r'])) {
											
									$rPage = $_POST['r'];
									$rCourse = $_POST['rC'];
											
									if ($rPage == "m"){
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/mailbox/Inbox.php$extraQ");	
									}elseif ($rPage == "hq"){   // Homework -> Quiz
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/homework/Quizzes.php?CourseID=$rCourse$extraA");	
									}elseif ($rPage == "hj"){   // Homework -> Journal
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/homework/JHList.php?CourseID=$rCourse$extraA");	
									}elseif ($rPage == "hw"){   // Homework -> Worksheet
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/homework/WHList.php?CourseID=$rCourse$extraA");	
									}elseif ($rPage == "hp"){   // Homework -> PMP
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/homework/PMPs.php?CourseID=$rCourse$extraA");	
									}elseif ($rPage == "hl"){   // Homework -> link
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/homework/LRList.php?CourseID=$rCourse$extraA");	
									}elseif ($rPage == "hr"){   // Homework -> resource
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/homework/LRList.php?CourseID=$rCourse$extraA");	
									}elseif ($rPage == "ha"){   // Homework -> annotation
										$SyllTypeName = $_POST['SyllabusType'];
										$CTopicID = $_POST['CTopicID'];
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/subjects/Contents.php?$SyllTypeName=".$CTopicID.$extraA);	
									}elseif ($rPage == "hg"){   // Homework -> resource
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/Games/IndexStu.php".$extraQ);	
									}elseif ($rPage == "he"){   // Homework -> PMP
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/homework/EAQz.php?CourseID=".$rCourse.$extraA);	
									}else{
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/subjects/index.php".$extraQ);
									}
									exit();		
								}else{
									if($_SESSION['SessionSchoolID']=="MC12")
									{
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/mathscompetition2013/index.php".$extraQ."&error=9");
									}
									else
									{
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/subjects/index.php".$extraQ);
									}
									exit();
								}
										
							}elseif ($_SESSION['SessionUserTypeID']==3){
								session_write_close();		
								if (isset($_POST['r'])) {
											
									$rPage = $_POST['r'];
									$rCourse = $_POST['rC'];
											
									if ($rPage == "m"){
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/mailbox/Inbox.php".$extraQ);	
									}else{
										header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/subjects/index.php".$extraQ);
									}
											
								}else{
									header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/subjects/index.php".$extraQ);
								}
									
									
							}else{
								header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/subjects/index.php".$extraQ);
							}
							exit();
						}
								
						mysql_close();
						exit();
						
					}else{ // Log for Other Users
						
						$Query = "INSERT INTO TBL_LogUsers (UserID, SessionID, ClientInfo, IPAddress, Referrer, LogIn, StatusID) VALUES (".$_SESSION['SessionUserID'].", '".session_id()."', '".$_SERVER['HTTP_USER_AGENT']."', '".GetUserIP()."', '".$_SERVER['HTTP_REFERER']."', Now(), 1)";	                
	                 	$Result = mysql_query($Query);
								session_write_close();
	                 	// Redirect user to homepage once authentication is complete	                 	
	                 	if ($_SESSION['SessionUserID']==3){
							header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/forum/IntNatForumTopic.php?FSID=aa5eb561705bb1be67f4013980ad1131&ForumID=1$extraA");
	                 	}else{
	                 		header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/home/index.php$extraQ");
	                	}
	                 	
		                mysql_close();
		                exit();
						
					}
					
                } else {
			   
			   
					//remember me .. clear cookie 
					if(!isset($_COOKIE[$cookie_name]))
					{
						header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/index.php?IP=1&U=".$_POST['Username']."$extraA");
					}
					else
					{
						setcookie ('aceLearningSiteAuth', '', time() - $cookie_time, '/');
						header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/index.php?IP=1&U=".trim($converter->decode($usernamecookie))."$extraA");
					}
					mysql_close();
					exit();
			   
                    $Str .= "<BR><BR><BR><BR>";
                    $Str .= "<table border=\"0\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\">\n";
					$Str .= "  <tr>\n";
					$Str .= "    <td width=\"100%\" align=\"center\">\n";
					$Str .= "      <p><font color=\"FF0000\"><b>You have entered an INVALID Password !</p></b>\n";
					$Str .= "    </td>\n";
					$Str .= "  </tr>\n";
					$Str .= "</table>\n";

                }

            // Username doesn't exist
            } else {
		    

			    //header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/status.php?IU=1$extraA");
			    //header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/". $SystemFolder . "/index.php?IU=1$extraA");
			    header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/index.php?IU=1$extraA");
			    mysql_close();
			    exit();
		    
                $_POST['Username'] = "";
               	$Str .= "<BR><BR><BR><BR>";
                $Str .= "<table border=\"0\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\">\n";
			    $Str .= "  <tr>\n";
			    $Str .= "    <td width=\"100%\" align=\"center\">\n";
			    $Str .= "      <p><font color=\"FF0000\"><b>You have entered an INVALID Username !</b></p>\n";
			    $Str .= "    </td>\n";
			    $Str .= "  </tr>\n";
			    $Str .= "</table>\n";

			}

        }

    } else {
 	  
 	  
		header ("Location:  http://" . $_SERVER['HTTP_HOST'] . "/index.php");
		mysql_close();
		exit();
 	  
     	$Str .= "<BR><BR><BR><BR>\n";
     	$Str .= "<table border=\"0\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\">\n";
     	$Str .= "  <tr>\n";
     	$Str .= "    <td width=\"100%\" align=\"center\">\n";
     	$Str .= "      <p>Welcome to <font color=\"FF0000\"><b>ACE-Learning</b></font>! Login Now!</p>\n";
     	$Str .= "    </td>\n";
     	$Str .= "  </tr>\n";
     	$Str .= "</table>\n";
     	  
    }

?>